services:
  ingress:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl
    networks:
      - nginx-network
    
  backoffice:
    image: gopenux/sistemas-formacion:latest
    environment:
      - PG_HOST=database
      - PG_PORT=5432
      - API_URL=https://restcountries.com/v3.1
    ports:
      - "5000:5000"
    secrets:
      - db_password
      - db_user
      - db_name
    networks:
      - nginx-network
      - database-network

  database:
    image: postgres:latest
    secrets:
      - db_password
      - db_user
      - db_name
    ports:
      - "5432:5432"
    networks:
      database-network:
        aliases:
          - db
    volumes:
      - ./database-data:/var/lib/postgresql/data
    deploy:
      replicas: 1

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_name:
    file: ./secrets/db_name.txt

networks: 
  nginx-network:
    driver: overlay
  database-network:
    driver: overlay