services:
  ingress:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /nginx/certs:/etc/nginx/ssl
    networks:
      nginx-network:
        aliases:
          - nginx-network
    deploy:
      replicas: 1
      placement:
        constraints: 
         - node.labels.role == nginx
    
  backoffice:
    image: gopenux/sistemas-formacion:latest
    environment:
      - PG_HOST=database
      - PG_PORT=5432
      - API_URL=https://restcountries.com/v3.1
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DB=country
    ports:
      - "5000:5000"
    networks:
      nginx-network:
        aliases:
          - backoffice-network
      database-network:
        aliases:
          - database-network
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=country
    networks:
      database-network:
        aliases:
          - db
    volumes:
      - /database-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.labels.role == database

networks: 
  nginx-network:
    driver: overlay
  database-network:
    driver: overlay
