services:
  ingress:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl
    networks:
      - nginx-network
    

  backoffice:
    image: gopenux/sistemas-formacion:latest
    ports:
      - "5000:5000"
    environment:
      PG_HOST: "database"
      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASSWORD: "password"
      PG_DB: "country"
    networks:
      - nginx-network
      - database-network
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "country"
    networks:
      - database-network
    volumes:
      - ./database-data:/var/lib/postgresql/data
    
networks: 
  nginx-network:
    driver: overlay
  database-network:
    driver: overlay